spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/study?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 3161

  devtools:
    remote:
      restart:
        enabled: true

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update # create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    properties:
      hibernate:
#        show-sql: true
        format_sql: true
        default_batch_fetch_size: 1000
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  mail:
    # Google smtp server 사용
    host: smtp.gmail.com
    port: 587
    username: k305059ute #앱 비밀번호 발급받은 google 계정
    password: zbzwmacanvmpamoq #발급받은 앱 비밀번호
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace