spring:
  datasource:
#    url: jdbc:h2:tcp://localhost/~/jpashop
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/study?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 3161

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    properties:
      hibernate:
#        show-sql: true
        format_sql: true
        default_batch_fetch_size: 1000
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  mail:
    host: smtp.naver.com #smtp 서버 주소
    port: 465 # 메일 인증서버 포트
    username: tim9ute #네이버 아이디
    password: tim6358? #네이버 비밀번호
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          #            required: true
          auth: true
          #          connectiontimeout: 5000
          #          timeout: 5000
          #          writetimeout: 5000
          ssl:
            #trust: smtp.naver.com
            enable: true #반드시 필요 -> SSL 필요로 되어있으면

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace